### ISSUE TITLE
RQL Console - How to reference the `exception.message` field?

### ISSUE THREAD

**Issue by s2t2** [rollbar/docs#23]
Hi, I'm enjoying the RQL Console, but running into an issue I'm hoping you can help resolve. The query, `SELECT * FROM item_occurrence` shows a field called `exception.message` but I'm unable to select/reference that field. How should I reference it?

<img width="409" alt="screenshot 2016-09-08 17 40 25" src="https://cloud.githubusercontent.com/assets/1328807/18368030/d6eb678c-75eb-11e6-8129-8ea9ac10e8a6.png">

<img width="456" alt="screenshot 2016-09-08 17 40 40" src="https://cloud.githubusercontent.com/assets/1328807/18368057/f610c3e6-75eb-11e6-861a-0bcf546d25a8.png">

**Comment by brianr** [comment]
Good question - this is confusing and we ideally should fix this in RQL. What's happening here is that `exception.message` is the shortened version of the actual field name, which is going to be one of the following:

- `body.trace.exception.message` (this is most common)
- `body.trace_chain.0.exception.message` (if you have a stack trace composed of multiple exceptions)

**Comment by s2t2** [comment]
`body.trace.exception.message` is working. thanks!

**Comment by s2t2** [comment]
ok, one last question: how can i access this field from the notification rule message template?  

those two names aren't working...

<img width="552" alt="screenshot 2016-09-09 15 28 38" src="https://cloud.githubusercontent.com/assets/1328807/18400072/45ca02ec-76a2-11e6-916f-537c64e45e8a.png">

**Comment by brianr** [comment]
@s2t2 try `body.body.trace.exception.message`. (To access data inside the occurrence from those, you have to add an extra `body.` prefix.)

**Comment by s2t2** [comment]
@brianr thanks, but `{{body.body.trace.exception.message}}` doesn't work inside the notification message template. were you able to get it working?
