### ISSUE TITLE
Notification Message Template - Variable Reference

### ISSUE THREAD

**Issue by s2t2** [rollbar/docs#34]
Hi. I'm having issues referencing variables within the notification template ([unresolved from this comment](https://github.com/rollbar/docs/issues/23#issuecomment-246015340)).

Variables I'm able to reference successfully include:

```` 
{{project_slug}}
{{environment}}
{{link}}
````

Variables I'm unable to to reference unsuccessfully include:

````
{{request.method}}
{{request.params}}
{{request.url}} 
{{body.trace.exception.message}}
{{body.trace.exception.class}}
{{body.trace.extra}}
{{person}}
````

Alternate unsuccessful attempts:

````
{{body.request.method}}
{{body.request.params}}
{{body.request.url}} 
{{body.body.trace.exception.message}}
{{body.body.trace.exception.class}}
{{body.body.trace.extra}}
{{body.person}}
````

````
{{exception}}
{{exception.message}}
{{exception.class}}
{{item}} 
````

````
{{body.trace_chain.0.exception.message}}
{{body}}
{{body.trace_chain.0}} 
````

Any guidance you can provide on how to reference these variables within the Notification Template would be very appreciated. 

Thank you!

**Comment by stclairdaniel** [comment]
Currently, only {{project_slug}}, {{environment}}, {{trigger_description}}, {{username}}, {{level}}, {{title}}, and {{link}} will be replaced. We've had a few other users make a request to  reference arbitrary variables inside double braces and it's on our radar. I'll make sure to let you know the status of this issue.

**Comment by s2t2** [comment]
ok thanks for the info!

**Comment by parisholley** [comment]
@jessewgibbs is this closed meaning that it is complete, on road map, not going to be implemented?
