### ISSUE TITLE
Rollbar.NET

### ISSUE THREAD

**Issue by supergibbs** [rollbar/docs#56]
The [docs](https://github.com/rollbar/docs/blob/master/onboarding/dotnet.md) say to use [RollbarSharp](https://github.com/mroach/RollbarSharp) but [Rollbar.NET](https://github.com/rollbar/Rollbar.NET) seem more official and updated more recently (though not for a few months). Which is the current recommendation?

**Comment by rivkahstandig3636** [comment]
Hi @supergibbs! Thanks for bringing this to our attention; we'll update those docs. The current recommendation is to use Rollbar.NET.

**Comment by rivkahstandig3636** [comment]
Fixed with #69

**Comment by psttf** [comment]
Am I right that at the moment RollbarSharp has more features when reporting errors from the web app?

As I understand RollbarSharp fills web properties of the error from `HttpContext.Current` whereas Rollbar.NET only reports the error message and stacktrace.

**Comment by rivkahstandig3636** [comment]
@psttf Yes, currently those features are not available in Rollbar.NET. They are on our radar to implement though. Sorry about that!
